const interpretacoes = {
    sol: {
      "Carneiro": "O Sol em Carneiro acende o espírito de um guerreiro, instigando a coragem primitiva que desafia o desconhecido. Como Heráclito disse, 'A guerra é o pai de todas as coisas', e a energia de Carneiro se manifesta na ação direta, no impulso para a mudança e a superação das adversidades.",
      "Touro": "O Sol em Touro irradia uma calma sólida, evocando a busca pela beleza duradoura e pela terra firme. Aristóteles afirmou que a felicidade reside na contemplação da beleza natural, e Touro, com sua apreciação pela simplicidade, busca viver de acordo com este princípio, cultivando serenidade e abundância.",
      "Gémeos": "O Sol em Gémeos é a chama da curiosidade e da comunicação incessante. Platão falava sobre a importância do diálogo como meio de entendimento, e o geminiano, com sua mente ágil, vê no conhecimento e na troca intelectual a chave para desvendar os mistérios da existência.",
      "Caranguejo": "O Sol em Caranguejo é a luz que aquece os laços afetivos e a memória ancestral. A filosofia de Confúcio revela que 'onde há amor, há vida', e o Caranguejo, regido pelo coração, encontra sua força na proteção e na profunda conexão com suas raízes e com os outros.",
      "Leão": "O Sol em Leão é a expressão do eu no seu esplendor. Nietzsche, em sua busca pelo 'Übermensch', buscava a liberdade e a criação do próprio destino, e Leão, com seu brilho natural, é aquele que se ergue, desafiando o mundo a reconhecê-lo e a aplaudir sua essência única.",
      "Virgem": "O Sol em Virgem é a luz que encontra perfeição no detalhamento e na ordem. Na busca platônica pela verdade e harmonia, Virgem reflete o desejo de transformar o mundo com a precisão da razão e o cuidado do serviço, enxergando a beleza no que é simples e prático.",
      "Balança": "O Sol em Balança busca a verdade na harmonia das relações. Aristóteles falava sobre o 'justo meio', e Balança, com sua sensibilidade à estética e à justiça, busca o equilíbrio entre os opostos, onde a beleza e a equidade se entrelaçam para criar paz e entendimento.",
      "Escorpião": "O Sol em Escorpião é a força da transformação, um mergulho profundo nas águas sombrias da alma. A filosofia de Kierkegaard fala da 'angústia existencial', e Escorpião, com sua intensidade, busca a verdade nos recantos mais profundos do ser, desafiando as sombras e buscando o renascimento.",
      "Sagitário": "O Sol em Sagitário é a chama da liberdade, da busca incessante por sabedoria e aventura. Como disse Rainer Maria Rilke, 'Viver significa buscar'. O sagitariano, com sua alma expansiva, é um eterno peregrino da verdade, que se aventura sem medo nas vastidões do desconhecido.",
      "Capricórnio": "O Sol em Capricórnio é a luz da perseverança e da responsabilidade. O filósofo Lao Tzu ensinou que 'um homem de verdade é forte como uma rocha', e Capricórnio, com seu foco e disciplina, constrói o futuro com a paciência dos que sabem que nada de valor é conquistado sem esforço.",
      "Aquário": "O Sol em Aquário ilumina o caminho da inovação e do progresso coletivo. Como Rousseau acreditava, a liberdade é o pilar da humanidade, e Aquário, com sua visão futurista, busca transformar o mundo para o bem comum, sempre à frente de seu tempo, inspirado pela ideia de uma nova utopia.",
      "Peixes": "O Sol em Peixes é o mergulho no mistério da alma e do cosmos. 'O mundo é uma alma', dizia Platão, e Peixes, com sua conexão profunda com o espiritual e o emocional, traz uma energia que flui entre as dimensões do ser, buscando compreender os mistérios da vida através da empatia e da intuição."
    },
    lua: {
        "Carneiro": "A Lua em Carneiro é impulsiva e emocionalmente ativa. A necessidade de ação e novidade guia os sentimentos, fazendo com que a pessoa reaja de forma intensa e espontânea às emoções.",
        "Touro": "A Lua em Touro busca conforto e segurança emocional através da estabilidade e das sensações físicas. A pessoa sente-se profundamente conectada à natureza e ao prazer material, com um forte desejo de construir uma vida tranquila e próspera.",
        "Gémeos": "A Lua em Gémeos é curiosa e intelectualmente envolvida. A pessoa tem um desejo de explorar suas emoções por meio da comunicação e da troca de ideias, sendo adaptável e versátil em seus sentimentos.",
        "Caranguejo": "A Lua em Caranguejo é profundamente emocional e protetora. Os sentimentos são intensos, com uma forte ligação à família e ao lar. A necessidade de segurança emocional é primordial e a pessoa busca sempre nutrir e cuidar dos outros.",
        "Leão": "A Lua em Leão é dramática e busca expressão emocional através da criatividade e do reconhecimento. Existe um forte desejo de ser admirado e valorizado, e a pessoa sente grande prazer ao compartilhar seu amor e afeição com os outros.",
        "Virgem": "A Lua em Virgem é analítica e busca segurança emocional por meio da ordem e do serviço. As emoções são processadas de maneira prática e meticulosa, com um desejo de aperfeiçoamento constante e de cuidar dos outros de forma tangível.",
        "Balança": "A Lua em Balança busca harmonia e equilíbrio nos relacionamentos emocionais. A pessoa se sente emocionalmente realizada quando está em parceria, buscando constantemente a paz, o amor e a beleza nas interações.",
        "Escorpião": "A Lua em Escorpião é intensa e profundamente transformadora. Os sentimentos são experimentados com grande profundidade, e a pessoa tem uma necessidade de privacidade emocional. A busca pela verdade e pela autenticidade é fundamental para a saúde emocional.",
        "Sagitário": "A Lua em Sagitário é otimista e busca liberdade emocional. Os sentimentos são amplificados pela aventura, pela busca de significado e pela expansão de horizontes. A pessoa se sente emocionalmente realizada quando está em movimento e explorando o desconhecido.",
        "Capricórnio": "A Lua em Capricórnio é reservada e controlada emocionalmente. A segurança emocional é encontrada na estrutura, no trabalho e na conquista de objetivos. Existe uma necessidade de se sentir realizado e seguro através de suas ambições e responsabilidades.",
        "Aquário": "A Lua em Aquário é intelectual e desapegada. As emoções são processadas de maneira lógica e objetiva, com um desejo de independência emocional. A pessoa pode sentir um forte impulso de ser única e expressar suas ideias de maneira inovadora.",
        "Peixes": "A Lua em Peixes é profundamente intuitiva e sensível. Os sentimentos são experimentados de forma fluida e muitas vezes inconstante, com uma necessidade de se conectar ao mundo espiritual e a emoções mais profundas. A pessoa busca a cura e o entendimento emocional por meio da empatia e da compaixão."
    },      
    venus: {
      "Carneiro": "Vénus em Carneiro expressa um amor ardente e direto. Apaixona-se rapidamente e busca aventura e espontaneidade nas relações.",
      "Touro": "Vénus em Touro é sensual e busca segurança no amor. Valorizam-se gestos simples e toques que expressam afeição.",
      "Gémeos": "Vénus em Gémeos encanta com palavras e curiosidade. O amor é leve, divertido e cheio de descobertas.",
      "Caranguejo": "Vénus em Caranguejo é profundamente emocional, buscando nutrição e conexão no amor.",
      "Leão": "Vénus em Leão é apaixonado e dramático, com uma necessidade de ser admirado e amado intensamente.",
      "Virgem": "Vénus em Virgem é discreto e dedicado no amor. Expressa afeição por meio de cuidados e atenção aos detalhes.",
      "Balança": "Vénus em Balança é elegante e diplomático, valorizando a harmonia e a beleza nas relações.",
      "Escorpião": "Vénus em Escorpião é intensa e transformadora, com um amor que vai além da superfície e busca profundidade.",
      "Sagitário": "Vénus em Sagitário ama a liberdade e a aventura. Relações baseiam-se em crescimento mútuo e exploração.",
      "Capricórnio": "Vénus em Capricórnio é leal e pragmático, buscando segurança e estabilidade nas relações.",
      "Aquário": "Vénus em Aquário valoriza a independência e a amizade no amor. Relações são únicas e progressistas.",
      "Peixes": "Vénus em Peixes é romântica e compassiva, amando de forma incondicional e com profunda empatia."
    },
    marte: {
      "Carneiro": "Marte em Carneiro é uma explosão de energia e determinação. Ação imediata e coragem marcam seu caminho.",
      "Touro": "Marte em Touro é persistente e paciente, com uma força constante voltada para conquistas práticas.",
      "Gémeos": "Marte em Gémeos é ágil e cheio de ideias. A energia é canalizada para comunicação e aprendizado.",
      "Caranguejo": "Marte em Caranguejo age com emoção, defendendo ferozmente aquilo que ama.",
      "Leão": "Marte em Leão é determinado e criativo, movido pelo desejo de expressar-se plenamente.",
      "Virgem": "Marte em Virgem é meticuloso e eficiente, com energia focada na melhoria contínua.",
      "Balança": "Marte em Balança busca equilíbrio e harmonia, movendo-se com estratégia em vez de força bruta.",
      "Escorpião": "Marte em Escorpião é intenso e implacável, com uma energia transformadora que nunca desiste.",
      "Sagitário": "Marte em Sagitário é aventureiro e otimista, sempre em busca de novas jornadas.",
      "Capricórnio": "Marte em Capricórnio é disciplinado e trabalhador, alcançando objetivos com perseverança.",
      "Aquário": "Marte em Aquário é inovador e progressista, canalizando energia para mudanças significativas.",
      "Peixes": "Marte em Peixes é intuitivo e sensível, movendo-se com empatia e criatividade."
    },
    jupiter: {
      "Carneiro": "Júpiter em Carneiro expande a coragem e a liderança. É uma energia de inspiração para começar novos projetos e enfrentar desafios com entusiasmo.",
      "Touro": "Júpiter em Touro traz prosperidade material e um amor pela natureza. Busca estabilidade e conforto em um crescimento constante.",
      "Gémeos": "Júpiter em Gémeos amplia a curiosidade e o desejo de aprender. A comunicação e o pensamento criativo são favorecidos.",
      "Caranguejo": "Júpiter em Caranguejo expande o cuidado emocional e a ligação familiar. Uma energia que promove proteção e empatia.",
      "Leão": "Júpiter em Leão traz confiança e brilho. Expande a criatividade, o carisma e o desejo de ser reconhecido.",
      "Virgem": "Júpiter em Virgem amplia a busca pela perfeição e pela ordem. Favorece o crescimento por meio do trabalho dedicado e meticuloso.",
      "Balança": "Júpiter em Balança promove justiça, equilíbrio e harmonia. O crescimento ocorre nas relações e na busca por beleza.",
      "Escorpião": "Júpiter em Escorpião é intenso e transformador. Expande a capacidade de regeneração e o entendimento emocional profundo.",
      "Sagitário": "Júpiter em Sagitário é aventureiro e filosófico. Promove a expansão do conhecimento e a busca por liberdade.",
      "Capricórnio": "Júpiter em Capricórnio traz crescimento através da disciplina e do trabalho árduo. Favorece o alcance de metas a longo prazo.",
      "Aquário": "Júpiter em Aquário amplia a inovação e o pensamento progressista. Promove mudanças que beneficiam o coletivo.",
      "Peixes": "Júpiter em Peixes traz empatia e espiritualidade. Expande a conexão emocional e a compreensão intuitiva do mundo."
    },
    saturno: {
      "Carneiro": "Saturno em Carneiro ensina disciplina na liderança e na ação. Aprender a controlar impulsos é o caminho para o crescimento.",
      "Touro": "Saturno em Touro traz lições sobre paciência e estabilidade. O crescimento vem da perseverança e da valorização do que é duradouro.",
      "Gémeos": "Saturno em Gémeos ensina a estruturar ideias e a comunicar-se de maneira clara e eficaz. O aprendizado é um processo gradual.",
      "Caranguejo": "Saturno em Caranguejo desafia a lidar com as emoções e a construir segurança emocional. Lições profundas sobre o lar e a família.",
      "Leão": "Saturno em Leão desafia o ego e a expressão criativa. O crescimento ocorre ao equilibrar autoconfiança com responsabilidade.",
      "Virgem": "Saturno em Virgem ensina a importância dos detalhes e da organização. Crescer exige disciplina e trabalho meticuloso.",
      "Balança": "Saturno em Balança promove lições sobre relacionamentos e equilíbrio. Ensina a estabelecer conexões duradouras e justas.",
      "Escorpião": "Saturno em Escorpião traz lições de transformação e resiliência. Crescer exige enfrentar medos profundos e mudar.",
      "Sagitário": "Saturno em Sagitário ensina a responsabilidade na busca por conhecimento e liberdade. Crescimento exige disciplina na exploração de novas ideias.",
      "Capricórnio": "Saturno em Capricórnio está em casa, trazendo lições sobre trabalho árduo e responsabilidade. Crescimento ocorre com ambição estruturada.",
      "Aquário": "Saturno em Aquário ensina a equilibrar inovação com responsabilidade social. O progresso vem da persistência em ideias originais.",
      "Peixes": "Saturno em Peixes traz lições sobre disciplina espiritual e emocional. O crescimento ocorre ao equilibrar sonhos com realidade."
    },
    urano: {
      "Carneiro": "Urano em Carneiro traz inovações ousadas e um espírito pioneiro. Mudanças ocorrem por meio da ação direta e corajosa.",
      "Touro": "Urano em Touro revoluciona valores e estabilidade material. Traz mudanças inesperadas na busca por conforto e segurança.",
      "Gémeos": "Urano em Gémeos promove inovação na comunicação e no aprendizado. Idéias revolucionárias surgem de conexões rápidas.",
      "Caranguejo": "Urano em Caranguejo transforma o lar e as emoções. Mudanças radicais ocorrem na forma de se conectar emocionalmente.",
      "Leão": "Urano em Leão promove criatividade única e originalidade. As mudanças surgem da expressão autêntica do ser.",
      "Virgem": "Urano em Virgem inova no trabalho e na saúde. Mudanças transformam rotinas e sistemas de organização.",
      "Balança": "Urano em Balança revoluciona os relacionamentos e a busca por harmonia. Promove novas formas de conexão.",
      "Escorpião": "Urano em Escorpião traz transformações profundas e mudanças inesperadas nas emoções e na psique.",
      "Sagitário": "Urano em Sagitário revoluciona crenças e filosofias. Mudanças surgem da exploração de novos horizontes.",
      "Capricórnio": "Urano em Capricórnio transforma estruturas e sistemas tradicionais. Revolução ocorre nas áreas de trabalho e governo.",
      "Aquário": "Urano em Aquário está em casa, trazendo inovações radicais e mudanças no coletivo. O progresso é a prioridade.",
      "Peixes": "Urano em Peixes promove transformações espirituais e intuitivas. Mudanças ocorrem nas percepções e sonhos."
    },
    neptuno: {
      "Carneiro": "Neptuno em Carneiro inspira ação guiada pela intuição. Sonhos são perseguidos com coragem.",
      "Touro": "Neptuno em Touro traz sensibilidade à beleza e aos prazeres terrenos. O mundo espiritual conecta-se com o material.",
      "Gémeos": "Neptuno em Gémeos amplia a imaginação e a intuição na comunicação. Sonhos surgem em palavras e ideias.",
      "Caranguejo": "Neptuno em Caranguejo promove profunda empatia e ligação emocional. Sonhos estão centrados na segurança emocional.",
      "Leão": "Neptuno em Leão inspira criatividade artística e visão espiritual. Sonhos são expressos com brilho.",
      "Virgem": "Neptuno em Virgem combina sensibilidade espiritual com trabalho prático. Intuição guia a organização.",
      "Balança": "Neptuno em Balança sonha com harmonia e beleza universal. Relações são profundamente espirituais.",
      "Escorpião": "Neptuno em Escorpião mergulha na profundidade emocional. Sonhos são transformadores e intensos.",
      "Sagitário": "Neptuno em Sagitário inspira ideais elevados e conexão espiritual. Sonhos envolvem expansão e aventura.",
      "Capricórnio": "Neptuno em Capricórnio une espiritualidade com ambição. Sonhos manifestam-se de maneira tangível.",
      "Aquário": "Neptuno em Aquário traz visões de um futuro ideal. Sonhos conectam o coletivo e o espiritual.",
      "Peixes": "Neptuno em Peixes está em casa, trazendo profunda sensibilidade e conexão espiritual. Sonhos são ilimitados."
    },
    plutao: {
      "Carneiro": "Plutão em Carneiro transforma por meio da ação direta. O poder pessoal é despertado pela coragem.",
      "Touro": "Plutão em Touro renova valores e segurança material. Transformações ocorrem lentamente, mas de forma profunda.",
      "Gémeos": "Plutão em Gémeos transforma ideias e comunicação. Mudanças radicais ocorrem na forma de pensar.",
      "Caranguejo": "Plutão em Caranguejo renova as bases emocionais e familiares. Transformação ocorre na segurança interna.",
      "Leão": "Plutão em Leão transforma a criatividade e o ego. O poder surge da expressão autêntica do ser.",
      "Virgem": "Plutão em Virgem renova métodos e rotinas. Transformações profundas ocorrem no trabalho e na saúde.",
      "Balança": "Plutão em Balança transforma as relações e a busca por equilíbrio. Poder surge do entendimento mútuo.",
      "Escorpião": "Plutão em Escorpião está em casa, trazendo intensas transformações emocionais e espirituais.",
      "Sagitário": "Plutão em Sagitário renova crenças e filosofias. Transformações ocorrem na busca por sentido e liberdade.",
      "Capricórnio": "Plutão em Capricórnio transforma estruturas e sistemas. Poder surge da reinvenção de tradições.",
      "Aquário": "Plutão em Aquário transforma o coletivo e a inovação. O poder está em mudanças sociais profundas.",
      "Peixes": "Plutão em Peixes traz transformações espirituais e intuitivas. Poder surge da conexão com o inconsciente."
    },
    mercurio: {
      "Carneiro": "Mercúrio em Carneiro é direto e rápido na comunicação. A mente é ágil, com uma tendência a agir impulsivamente.",
      "Touro": "Mercúrio em Touro é prático e focado. Prefere pensar de forma mais lenta, ponderando as decisões com cautela.",
      "Gémeos": "Mercúrio em Gémeos é a expressão pura da curiosidade e adaptabilidade. A comunicação flui facilmente e a mente está sempre ativa.",
      "Caranguejo": "Mercúrio em Caranguejo é intuitivo e emocional na comunicação. A mente é influenciada pelo instinto e pela memória.",
      "Leão": "Mercúrio em Leão é dramático e criativo na comunicação. Expressa ideias com confiança e autoridade.",
      "Virgem": "Mercúrio em Virgem é analítico e detalhista. A mente se preocupa com a organização e com a eficiência na comunicação.",
      "Balança": "Mercúrio em Balança busca equilíbrio e harmonia nas palavras. É diplomático e procura evitar conflitos.",
      "Escorpião": "Mercúrio em Escorpião é profundo e investigativo. A comunicação é intensa e as palavras são usadas para transformar.",
      "Sagitário": "Mercúrio em Sagitário é filosófico e expansivo. A mente busca conhecimento e a comunicação é otimista e cheia de ideias.",
      "Capricórnio": "Mercúrio em Capricórnio é pragmático e focado. A comunicação é prática e voltada para o objetivo.",
      "Aquário": "Mercúrio em Aquário é original e inovador. A mente é aberta e a comunicação é voltada para mudanças sociais e intelectuais.",
      "Peixes": "Mercúrio em Peixes é intuitivo e sonhador. A comunicação flui com sensibilidade e inspiração."
    }
    // Adicionar interpretações para os outros planetas conforme necessário...
  };
